baseURL = 'http://cyfz11.com/'
languageCode = 'en-us'
title = 'Nothingness'
publishDir = "docs"
theme = "mainroad"
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]
