baseURL = 'http://cyfz11.com/'
languageCode = 'en-us'
title = 'Nothingness'
publishDir = "docs"
theme = "mainroad"

[menu]
[[menu.main]]
  identifier = 'posts'
  name = 'posts'
  pre = "<i class='fa fa-road'></i>"
  url = '/posts/'
  weight = -110
[[menu.main]]
  identifier = 'about'
  name = 'about me'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'
  weight = -90

[params]
  AuthorName = 'Alina'
  SidebarRecentLimit = 5


[Params.sidebar]
  home = "right"
  # list = "right"
  # Enable widgets in given order
  widgets = ["recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5 # Set the number of articles in the "Recent articles" widget
  categories_counter = true # Enable counter for each category in "Categories" widget
  tags_counter = false # Enable counter for each tag in "Tags" widget

[Params.widgets.social]
  # Enable parts of social widget